### ISSUE TITLE
Issues' labels

### ISSUE THREAD

**Issue by joseluisbolos** [springernature/frontend#2]
Github creates some labels by default, but those are arguably not very good in general, and in particular not very appropriate for a repo that is supposed to contain only issues.

There's a **brilliant** article about replacing the default labels with something saner, however it's oriented to projects that use issues as a replacement for a bug tracker, so it doesn't really apply to this repo I think:
[https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63)

Any ideas?

**Comment by dotcode** [comment]
We recently changed the purpose of this repo to become the frontend playbook, and created /frontend-catchup as the issues-only place for stuff to discuss at the weekly catchup.

Nice article though, and I'm well up for creating labels that allow us to more easily discover stuff.
