### ISSUE TITLE
Create effective colour contrast page

### ISSUE THREAD

**Issue by dotcode** [springernature/frontend#64]
Recreate the "[Effective colour contrast]" page here, and link to it from guideline 3 in the [accessibility checklist].

[Effective colour contrast]: http://powerplant.nature.com/wiki/pages/viewpage.action?title=Effective+colour+contrast&spaceKey=JPCIS
[accessibility checklist]: /practices/accessibility-checklist.md

**Comment by umaar** [comment]
Seeing a broken link for `/practices/accessibility-checklist.md`
