### ISSUE TITLE
Should /languages be /technologies?

### ISSUE THREAD

**Issue by jpw** [springernature/frontend#83]
Seems a little confusing, especially as I want to create a "markup" page in there... also in my mind it clashes with the lovely new practices/language.md page which is about human languages.

**Comment by dotcode** [comment]
Good point.

**Comment by andrewmee** [comment]
Yeah technologies probably is a better choice of language.

**Comment by jpw** [comment]
https://github.com/springernature/frontend/pull/84

**Comment by jpw** [comment]
Changed merged as per https://github.com/springernature/frontend/pull/84
