### ISSUE TITLE
: VS ::

### ISSUE THREAD

**Issue by mparpaillon** [springernature/frontend#92]
Hi,

I see in your CSS documentation that you use ":" for your pseudo-elements (before, after) as for your pseudo selectors (hover, focus).

CSS 3 specifications say that pseudo-elements should be differenciated with two colons "::"
See this [article](https://css-tricks.com/almanac/selectors/a/after-and-before/#article-header-id-0) from CSS Tricks.

Single colons are often used to support IE8 though. But the correct syntax is "::" for pseudo-elements.

**Comment by dotcode** [comment]
Interesting! Thanks @mparpaillon - we'll discuss at our next group meeting, and provide feedback here.

**Comment by dotcode** [comment]
Actually ... looking at this, I think this was just a typo, rather than a recommendation! Will fix :)

**Comment by dotcode** [comment]
Thanks for your help @mparpaillon, nice catch :)
